CREATE TABLE servers (
    id         BIGSERIAL   PRIMARY KEY,
    name       VARCHAR(100) UNIQUE NOT NULL,
    pvp_type   VARCHAR(30) NOT NULL DEFAULT 'OPTIONAL_PVP',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);