CREATE TABLE hunt_sessions (
    id            BIGSERIAL    PRIMARY KEY,
    character_id  BIGINT       NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    location      VARCHAR(255),
    is_party      BOOLEAN      NOT NULL DEFAULT FALSE,
    notes         TEXT,
    started_at    TIMESTAMPTZ  NOT NULL,
    ended_at      TIMESTAMPTZ  NOT NULL,
    duration      VARCHAR(50)  NOT NULL,
    raw_xp        INTEGER      NOT NULL,
    xp_with_bonus INTEGER      NOT NULL,
    loot_total    INTEGER      NOT NULL,
    supplies      INTEGER      NOT NULL,
    damage        INTEGER      NOT NULL,
    healing       INTEGER      NOT NULL,
    char_level    INTEGER,
    ally_ek_level INTEGER,
    ally_ms_level INTEGER,
    ally_ed_level INTEGER,
    ally_rp_level INTEGER,
    ally_em_level INTEGER
);
